AWSTemplateFormatVersion: "2010-09-09"
Description: "This template creates the macro"
Parameters:
  FunctionArn:
    Type: String
Resources:
  CloudTrailBucketMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: CloudTrailBucket
      FunctionName: !Ref FunctionArn