AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    MyFunctionArn:
      Type: String
      Description: The ARN of the lambda function
    MyBucketName:
      Type: String
      Description: The name of the bucket to create
Resources:
  MyCustomResource:
      Type: Custom::CreateBucketWithData
      Version: "1.0"
      Properties:
        ServiceToken: !Ref MyFunctionArn
        BucketName: !Ref MyBucketName